replicaCount: 3  # Native HA: 3 replicas (1 active + 2 standby)

resources:
  limits:
    cpu: "4"
    memory: 16Gi
  requests:
    cpu: "2"
    memory: 8Gi

persistence:
  size: 200Gi

mqsc: |
  DEFINE QLOCAL('STAGE.QUEUE.1') REPLACE DEFPSIST(YES)
  DEFINE QLOCAL('STAGE.QUEUE.2') REPLACE DEFPSIST(YES)
  DEFINE QLOCAL('STAGE.DEAD.LETTER.QUEUE') REPLACE DEFPSIST(YES)
  DEFINE CHANNEL('STAGE.APP.SVRCONN') CHLTYPE(SVRCONN) REPLACE
  SET CHLAUTH('STAGE.APP.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody')
  SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS)
  SET CHLAUTH('STAGE.APP.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
  ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
  REFRESH SECURITY TYPE(CONNAUTH)
  DEFINE LISTENER('STAGE.LISTENER.TCP') TRPTYPE(TCP) PORT(1414) REPLACE
  START LISTENER('STAGE.LISTENER.TCP')
